services:
  shh6-wallos:
    image: bellamy/wallos:5.7.1
    container_name: shh6-wallos
    restart: unless-stopped
    ports:
      - "18806:80"
    volumes:
      - /Volume*/DockerAppData/shh6-wallos/data:/var/www/html/db
      - /Volume*/DockerAppData/shh6-wallos/logos:/var/www/html/images/uploads/logos
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M

x-app-meta:
  web:
    port: 18806
    protocol: http
